---
title: Dogs Unleashed
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Elise Atkin
email: 
description: Dog walking specialist in Lancaster, England.
baseurl: ''
url: https://dogs-unleashed.co.uk
twitter_username: 
github_username: 
instagram_username: 
theme: minima
plugins:
- jekyll-feed
